name = "jarvis-worker"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
BOT_NAME = "Джарвис"
TIMEZONE_OFFSET = "3"

[[d1_databases]]
binding = "DB"
database_name = "jarvis-db"
database_id = "11709f78-4dec-49bb-8e4a-ff42b16223b4"
migrations_dir = "db/migrations"

[ai]
binding = "AI"

[triggers]
crons = ["* * * * *"]
